export const siteConfig = {
    name: `Capture A Trip`,
    title: {
        default: `Capture A Trip - Book Tours Packages, Backpacking Adventures, & International Trips`,
    },
    description: `Explore Incredible Tour Packages, Group Tour, Trekking, International tour Package with Capture A Trip. We offer best travel itineraries for your perfect journey`,
    URL: process.env.NEXT_PUBLIC_BASE_URL || `https://www.captureatrip.com`,
    ogImage: `${process.env.NEXT_PUBLIC_BASE_URL}/og.jpg` || `https://www.captureatrip.com/og.jpg`,
    keywords: [
        "tour packages in India",
        "leh ladakh tour packages",
        "group tours in India",
        "trekking tours in India",
        "budget tours in India",
        "tourist places in India",
        " tourism in India",
        "tourism in India",
        " places to visit in India",
        "explore locations in ladakh",
        "India tourism",
        "holidays in India",
        "India destinations",
        " tourist places in India",
        "travel packages",
        "trekking tours in India",
        "Road trips in India",
        "Explore off beat destinations in India",
        "Tour Packages in India",
        "Group tours in India",
        "Trekking tours in India",
        "Treks in India",
        "Budget tours in India",
        "Tourist places in India",
        "Tourism in India",
        " Budget travel in India",
        "Bike tours in India",
        "Incredible India",
        "places to visit in India",
        "Tourism in India",
        "Places to visit in India",
        "Explore locations in Budget",
        "travel in India",
        "India Tourism",
        "Holidays in India",
        "India Destinations",
        "Weekend Getaways",
        "Road trips in India",
        "Ride out road trips",
        "Budget Travel India",
        "Tourist places in India",
        " Taxis in India",
        "Bike Rentals in India",
        "Self Drive trips",
        "Book outstation Taxi",
        "Bike Rentals",
        " End to end Travel Organization",
    ],
}

export type SiteConfig = typeof siteConfig